/**
 * WorldXI Player Dataset
 * Organized by Nation for easy filtering
 * Source: Confirmed World Cup 2026 squads
 */

export const NATIONS = {
  France: [
    { id: "fr_001", name: "Mike Maignan", pos: "GK", age: 29, nation: "France", club: "AC Milan", price: 5.5, photo: "https://media.api-sports.io/football/players/37145.png" },
    { id: "fr_002", name: "Brice Samba", pos: "GK", age: 30, nation: "France", club: "Rennes", price: 4.5, photo: "https://media.api-sports.io/football/players/22528.png" },
    { id: "fr_003", name: "Robin Risser", pos: "GK", age: 23, nation: "France", club: "Lens", price: 4.0, photo: "https://media.api-sports.io/football/players/284087.png" },
    { id: "fr_004", name: "William Saliba", pos: "DEF", age: 25, nation: "France", club: "Arsenal", price: 6.0, photo: "https://media.api-sports.io/football/players/161612.png" },
    { id: "fr_005", name: "Dayot Upamecano", pos: "DEF", age: 26, nation: "France", club: "Bayern Munich", price: 5.5, photo: "https://media.api-sports.io/football/players/89547.png" },
    { id: "fr_006", name: "Jules Kounde", pos: "DEF", age: 26, nation: "France", club: "Barcelona", price: 6.0, photo: "https://media.api-sports.io/football/players/169798.png" },
    { id: "fr_007", name: "Ibrahima Konate", pos: "DEF", age: 25, nation: "France", club: "Liverpool", price: 5.5, photo: "https://media.api-sports.io/football/players/161609.png" },
    { id: "fr_008", name: "Theo Hernandez", pos: "DEF", age: 27, nation: "France", club: "Al Hilal", price: 6.5, photo: "https://media.api-sports.io/football/players/168529.png" },
    { id: "fr_009", name: "Lucas Hernandez", pos: "DEF", age: 28, nation: "France", club: "PSG", price: 5.5, photo: "https://media.api-sports.io/football/players/155807.png" },
    { id: "fr_010", name: "Lucas Digne", pos: "DEF", age: 31, nation: "France", club: "Aston Villa", price: 5.0, photo: "https://media.api-sports.io/football/players/37234.png" },
    { id: "fr_011", name: "Malo Gusto", pos: "DEF", age: 22, nation: "France", club: "Chelsea", price: 5.0, photo: "https://media.api-sports.io/football/players/350498.png" },
    { id: "fr_012", name: "Maxence Lacroix", pos: "DEF", age: 24, nation: "France", club: "Crystal Palace", price: 4.5, photo: "https://media.api-sports.io/football/players/276320.png" },
    { id: "fr_013", name: "Aurelien Tchouameni", pos: "MID", age: 25, nation: "France", club: "Real Madrid", price: 7.0, photo: "https://media.api-sports.io/football/players/342029.png" },
    { id: "fr_014", name: "N'Golo Kante", pos: "MID", age: 35, nation: "France", club: "Fenerbahce", price: 6.0, photo: "https://media.api-sports.io/football/players/1268.png" },
    { id: "fr_015", name: "Warren Zaire-Emery", pos: "MID", age: 20, nation: "France", club: "PSG", price: 6.0, photo: "https://media.api-sports.io/football/players/478123.png" },
    { id: "fr_016", name: "Adrien Rabiot", pos: "MID", age: 30, nation: "France", club: "AC Milan", price: 5.5, photo: "https://media.api-sports.io/football/players/2295.png" },
    { id: "fr_017", name: "Manu Kone", pos: "MID", age: 23, nation: "France", club: "Roma", price: 5.0, photo: "https://media.api-sports.io/football/players/387018.png" },
    { id: "fr_018", name: "Kylian Mbappe", pos: "FWD", age: 27, nation: "France", club: "Real Madrid", price: 14.5, photo: "https://media.api-sports.io/football/players/278.png" },
    { id: "fr_019", name: "Ousmane Dembele", pos: "FWD", age: 27, nation: "France", club: "PSG", price: 10.5, photo: "https://media.api-sports.io/football/players/18782.png" },
    { id: "fr_020", name: "Michael Olise", pos: "FWD", age: 23, nation: "France", club: "Bayern Munich", price: 9.0, photo: "https://media.api-sports.io/football/players/282680.png" },
    { id: "fr_021", name: "Marcus Thuram", pos: "FWD", age: 27, nation: "France", club: "Inter Milan", price: 8.5, photo: "https://media.api-sports.io/football/players/164468.png" },
    { id: "fr_022", name: "Desire Doue", pos: "FWD", age: 20, nation: "France", club: "PSG", price: 7.5, photo: "https://media.api-sports.io/football/players/452186.png" },
    { id: "fr_023", name: "Rayan Cherki", pos: "FWD", age: 21, nation: "France", club: "Manchester City", price: 7.0, photo: "https://media.api-sports.io/football/players/328762.png" },
    { id: "fr_024", name: "Bradley Barcola", pos: "FWD", age: 22, nation: "France", club: "PSG", price: 7.0, photo: "https://media.api-sports.io/football/players/387022.png" },
    { id: "fr_025", name: "Jean-Philippe Mateta", pos: "FWD", age: 27, nation: "France", club: "Crystal Palace", price: 6.5, photo: "https://media.api-sports.io/football/players/168527.png" },
    { id: "fr_026", name: "Maghnes Akliouche", pos: "FWD", age: 22, nation: "France", club: "Monaco", price: 6.0, photo: "https://media.api-sports.io/football/players/403218.png" },
  ],

  England: [
    { id: "en_001", name: "Jordan Pickford", pos: "GK", age: 32, nation: "England", club: "Everton", price: 5.5, photo: "https://media.api-sports.io/football/players/19220.png" },
    { id: "en_002", name: "Dean Henderson", pos: "GK", age: 29, nation: "England", club: "Crystal Palace", price: 4.5, photo: "https://media.api-sports.io/football/players/155826.png" },
    { id: "en_003", name: "James Trafford", pos: "GK", age: 22, nation: "England", club: "Manchester City", price: 4.0, photo: "https://media.api-sports.io/football/players/387502.png" },
    { id: "en_004", name: "Reece James", pos: "DEF", age: 25, nation: "England", club: "Chelsea", price: 6.0, photo: "https://media.api-sports.io/football/players/183665.png" },
    { id: "en_005", name: "John Stones", pos: "DEF", age: 31, nation: "England", club: "Manchester City", price: 6.0, photo: "https://media.api-sports.io/football/players/603.png" },
    { id: "en_006", name: "Marc Guehi", pos: "DEF", age: 24, nation: "England", club: "Manchester City", price: 5.5, photo: "https://media.api-sports.io/football/players/283087.png" },
    { id: "en_007", name: "Ezri Konsa", pos: "DEF", age: 27, nation: "England", club: "Aston Villa", price: 5.0, photo: "https://media.api-sports.io/football/players/173765.png" },
    { id: "en_008", name: "Dan Burn", pos: "DEF", age: 32, nation: "England", club: "Newcastle", price: 4.5, photo: "https://media.api-sports.io/football/players/19245.png" },
    { id: "en_009", name: "Jarell Quansah", pos: "DEF", age: 21, nation: "England", club: "Bayer Leverkusen", price: 4.5, photo: "https://media.api-sports.io/football/players/414328.png" },
    { id: "en_010", name: "Nico O'Reilly", pos: "DEF", age: 20, nation: "England", club: "Manchester City", price: 4.5, photo: "https://media.api-sports.io/football/players/482341.png" },
    { id: "en_011", name: "Djed Spence", pos: "DEF", age: 24, nation: "England", club: "Tottenham", price: 4.5, photo: "https://media.api-sports.io/football/players/307520.png" },
    { id: "en_012", name: "Tino Livramento", pos: "DEF", age: 22, nation: "England", club: "Newcastle", price: 4.5, photo: "https://media.api-sports.io/football/players/342027.png" },
    { id: "en_013", name: "Jude Bellingham", pos: "MID", age: 22, nation: "England", club: "Real Madrid", price: 12.0, photo: "https://media.api-sports.io/football/players/313556.png" },
    { id: "en_014", name: "Declan Rice", pos: "MID", age: 26, nation: "England", club: "Arsenal", price: 8.5, photo: "https://media.api-sports.io/football/players/225235.png" },
    { id: "en_015", name: "Kobbie Mainoo", pos: "MID", age: 19, nation: "England", club: "Manchester United", price: 6.5, photo: "https://media.api-sports.io/football/players/414820.png" },
    { id: "en_016", name: "Jordan Henderson", pos: "MID", age: 35, nation: "England", club: "Brentford", price: 5.0, photo: "https://media.api-sports.io/football/players/627.png" },
    { id: "en_017", name: "Morgan Rogers", pos: "MID", age: 22, nation: "England", club: "Aston Villa", price: 5.5, photo: "https://media.api-sports.io/football/players/350503.png" },
    { id: "en_018", name: "Elliot Anderson", pos: "MID", age: 21, nation: "England", club: "Nottingham Forest", price: 5.0, photo: "https://media.api-sports.io/football/players/374766.png" },
    { id: "en_019", name: "Harry Kane", pos: "FWD", age: 32, nation: "England", club: "Bayern Munich", price: 12.5, photo: "https://media.api-sports.io/football/players/184.png" },
    { id: "en_020", name: "Marcus Rashford", pos: "FWD", age: 28, nation: "England", club: "Barcelona", price: 9.0, photo: "https://media.api-sports.io/football/players/18846.png" },
    { id: "en_021", name: "Bukayo Saka", pos: "FWD", age: 24, nation: "England", club: "Arsenal", price: 9.5, photo: "https://media.api-sports.io/football/players/236670.png" },
    { id: "en_022", name: "Anthony Gordon", pos: "FWD", age: 24, nation: "England", club: "Liverpool", price: 7.5, photo: "https://media.api-sports.io/football/players/309536.png" },
    { id: "en_023", name: "Ollie Watkins", pos: "FWD", age: 29, nation: "England", club: "Aston Villa", price: 8.0, photo: "https://media.api-sports.io/football/players/186435.png" },
    { id: "en_024", name: "Ivan Toney", pos: "FWD", age: 29, nation: "England", club: "Al Ahli", price: 6.5, photo: "https://media.api-sports.io/football/players/225218.png" },
    { id: "en_025", name: "Levi Colwill", pos: "DEF", age: 22, nation: "England", club: "Chelsea", price: 5.0, photo: "https://media.api-sports.io/football/players/357633.png" },
    { id: "en_026", name: "Noni Madueke", pos: "FWD", age: 23, nation: "England", club: "Chelsea", price: 6.0, photo: "https://media.api-sports.io/football/players/350487.png" },
  ],

  Brazil: [
    { id: "br_001", name: "Alisson", pos: "GK", age: 32, nation: "Brazil", club: "Liverpool", price: 6.0, photo: "https://media.api-sports.io/football/players/1090.png" },
    { id: "br_002", name: "Ederson", pos: "GK", age: 31, nation: "Brazil", club: "Manchester City", price: 5.5, photo: "https://media.api-sports.io/football/players/9498.png" },
    { id: "br_003", name: "Weverton", pos: "GK", age: 36, nation: "Brazil", club: "Palmeiras", price: 4.0, photo: "https://media.api-sports.io/football/players/5913.png" },
    { id: "br_004", name: "Marquinhos", pos: "DEF", age: 31, nation: "Brazil", club: "PSG", price: 6.5, photo: "https://media.api-sports.io/football/players/369.png" },
    { id: "br_005", name: "Gabriel Magalhaes", pos: "DEF", age: 27, nation: "Brazil", club: "Arsenal", price: 6.0, photo: "https://media.api-sports.io/football/players/131273.png" },
    { id: "br_006", name: "Bremer", pos: "DEF", age: 27, nation: "Brazil", club: "Juventus", price: 5.5, photo: "https://media.api-sports.io/football/players/213064.png" },
    { id: "br_007", name: "Danilo Luiz", pos: "DEF", age: 33, nation: "Brazil", club: "Juventus", price: 5.0, photo: "https://media.api-sports.io/football/players/198.png" },
    { id: "br_008", name: "Alex Sandro", pos: "DEF", age: 33, nation: "Brazil", club: "Juventus", price: 4.5, photo: "https://media.api-sports.io/football/players/210.png" },
    { id: "br_009", name: "Wesley", pos: "DEF", age: 22, nation: "Brazil", club: "Aston Villa", price: 5.0, photo: "https://media.api-sports.io/football/players/388126.png" },
    { id: "br_010", name: "Roger Ibanez", pos: "DEF", age: 26, nation: "Brazil", club: "Al Ahli", price: 4.5, photo: "https://media.api-sports.io/football/players/247235.png" },
    { id: "br_011", name: "Douglas Santos", pos: "DEF", age: 29, nation: "Brazil", club: "Zenit", price: 4.5, photo: "https://media.api-sports.io/football/players/58773.png" },
    { id: "br_012", name: "Leo Pereira", pos: "DEF", age: 28, nation: "Brazil", club: "Flamengo", price: 4.5, photo: "https://media.api-sports.io/football/players/199058.png" },
    { id: "br_013", name: "Casemiro", pos: "MID", age: 34, nation: "Brazil", club: "Manchester United", price: 6.0, photo: "https://media.api-sports.io/football/players/632.png" },
    { id: "br_014", name: "Lucas Paqueta", pos: "MID", age: 27, nation: "Brazil", club: "Manchester City", price: 7.5, photo: "https://media.api-sports.io/football/players/163054.png" },
    { id: "br_015", name: "Bruno Guimaraes", pos: "MID", age: 27, nation: "Brazil", club: "Newcastle", price: 8.0, photo: "https://media.api-sports.io/football/players/204556.png" },
    { id: "br_016", name: "Fabinho", pos: "MID", age: 30, nation: "Brazil", club: "Al Ittihad", price: 5.5, photo: "https://media.api-sports.io/football/players/198672.png" },
    { id: "br_017", name: "Danilo Santos", pos: "MID", age: 23, nation: "Brazil", club: "Palmeiras", price: 5.0, photo: "https://media.api-sports.io/football/players/380120.png" },
    { id: "br_018", name: "Vinicius Jr", pos: "FWD", age: 24, nation: "Brazil", club: "Real Madrid", price: 13.5, photo: "https://media.api-sports.io/football/players/184390.png" },
    { id: "br_019", name: "Raphinha", pos: "FWD", age: 28, nation: "Brazil", club: "Barcelona", price: 10.0, photo: "https://media.api-sports.io/football/players/283064.png" },
    { id: "br_020", name: "Neymar", pos: "FWD", age: 34, nation: "Brazil", club: "Al Hilal", price: 9.5, photo: "https://media.api-sports.io/football/players/276.png" },
    { id: "br_021", name: "Gabriel Martinelli", pos: "FWD", age: 23, nation: "Brazil", club: "Arsenal", price: 8.5, photo: "https://media.api-sports.io/football/players/215914.png" },
    { id: "br_022", name: "Matheus Cunha", pos: "FWD", age: 25, nation: "Brazil", club: "Manchester United", price: 8.0, photo: "https://media.api-sports.io/football/players/283065.png" },
    { id: "br_023", name: "Endrick", pos: "FWD", age: 18, nation: "Brazil", club: "Real Madrid", price: 7.0, photo: "https://media.api-sports.io/football/players/419270.png" },
    { id: "br_024", name: "Luiz Henrique", pos: "FWD", age: 23, nation: "Brazil", club: "Real Betis", price: 6.0, photo: "https://media.api-sports.io/football/players/375786.png" },
    { id: "br_025", name: "Igor Thiago", pos: "FWD", age: 23, nation: "Brazil", club: "Club Brugge", price: 5.5, photo: "https://media.api-sports.io/football/players/383416.png" },
    { id: "br_026", name: "Rayan", pos: "FWD", age: 17, nation: "Brazil", club: "Flamengo", price: 5.0, photo: "https://media.api-sports.io/football/players/462109.png" },
  ],

  Germany: [
    { id: "de_001", name: "Manuel Neuer", pos: "GK", age: 40, nation: "Germany", club: "Bayern Munich", price: 5.0, photo: "https://media.api-sports.io/football/players/710.png" },
    { id: "de_002", name: "Oliver Baumann", pos: "GK", age: 34, nation: "Germany", club: "Hoffenheim", price: 4.0, photo: "https://media.api-sports.io/football/players/10291.png" },
    { id: "de_003", name: "Alexander Nubel", pos: "GK", age: 28, nation: "Germany", club: "Stuttgart", price: 4.5, photo: "https://media.api-sports.io/football/players/155817.png" },
    { id: "de_004", name: "Antonio Rudiger", pos: "DEF", age: 32, nation: "Germany", club: "Real Madrid", price: 6.5, photo: "https://media.api-sports.io/football/players/20547.png" },
    { id: "de_005", name: "Jonathan Tah", pos: "DEF", age: 29, nation: "Germany", club: "Bayern Munich", price: 5.5, photo: "https://media.api-sports.io/football/players/88.png" },
    { id: "de_006", name: "Nico Schlotterbeck", pos: "DEF", age: 25, nation: "Germany", club: "Borussia Dortmund", price: 5.5, photo: "https://media.api-sports.io/football/players/280695.png" },
    { id: "de_007", name: "David Raum", pos: "DEF", age: 26, nation: "Germany", club: "RB Leipzig", price: 5.0, photo: "https://media.api-sports.io/football/players/327556.png" },
    { id: "de_008", name: "Malick Thiaw", pos: "DEF", age: 23, nation: "Germany", club: "AC Milan", price: 5.0, photo: "https://media.api-sports.io/football/players/318825.png" },
    { id: "de_009", name: "Waldemar Anton", pos: "DEF", age: 28, nation: "Germany", club: "Stuttgart", price: 4.5, photo: "https://media.api-sports.io/football/players/155843.png" },
    { id: "de_010", name: "Nathaniel Brown", pos: "DEF", age: 21, nation: "Germany", club: "Bayern Munich", price: 4.5, photo: "https://media.api-sports.io/football/players/397124.png" },
    { id: "de_011", name: "Pascal Gross", pos: "DEF", age: 33, nation: "Germany", club: "Borussia Dortmund", price: 4.5, photo: "https://media.api-sports.io/football/players/19196.png" },
    { id: "de_012", name: "Joshua Kimmich", pos: "MID", age: 30, nation: "Germany", club: "Bayern Munich", price: 9.0, photo: "https://media.api-sports.io/football/players/716.png" },
    { id: "de_013", name: "Jamal Musiala", pos: "MID", age: 22, nation: "Germany", club: "Bayern Munich", price: 10.5, photo: "https://media.api-sports.io/football/players/303990.png" },
    { id: "de_014", name: "Florian Wirtz", pos: "MID", age: 22, nation: "Germany", club: "Bayer Leverkusen", price: 11.0, photo: "https://media.api-sports.io/football/players/284032.png" },
    { id: "de_015", name: "Leon Goretzka", pos: "MID", age: 30, nation: "Germany", club: "Bayern Munich", price: 6.5, photo: "https://media.api-sports.io/football/players/716.png" },
    { id: "de_016", name: "Leroy Sane", pos: "MID", age: 29, nation: "Germany", club: "Bayern Munich", price: 8.0, photo: "https://media.api-sports.io/football/players/726.png" },
    { id: "de_017", name: "Aleksandar Pavlovic", pos: "MID", age: 20, nation: "Germany", club: "Bayern Munich", price: 5.5, photo: "https://media.api-sports.io/football/players/393619.png" },
    { id: "de_018", name: "Maximilian Beier", pos: "MID", age: 22, nation: "Germany", club: "Borussia Dortmund", price: 5.5, photo: "https://media.api-sports.io/football/players/366083.png" },
    { id: "de_019", name: "Nadiem Amiri", pos: "MID", age: 28, nation: "Germany", club: "Genoa", price: 5.0, photo: "https://media.api-sports.io/football/players/18830.png" },
    { id: "de_020", name: "Jamie Leweling", pos: "MID", age: 23, nation: "Germany", club: "Stuttgart", price: 5.5, photo: "https://media.api-sports.io/football/players/362036.png" },
    { id: "de_021", name: "Angelo Stiller", pos: "MID", age: 23, nation: "Germany", club: "Stuttgart", price: 5.0, photo: "https://media.api-sports.io/football/players/366081.png" },
    { id: "de_022", name: "Felix Nmecha", pos: "MID", age: 24, nation: "Germany", club: "Borussia Dortmund", price: 5.0, photo: "https://media.api-sports.io/football/players/313558.png" },
    { id: "de_023", name: "Lennart Karl", pos: "MID", age: 21, nation: "Germany", club: "Augsburg", price: 4.5, photo: "https://media.api-sports.io/football/players/421056.png" },
    { id: "de_024", name: "Kai Havertz", pos: "FWD", age: 26, nation: "Germany", club: "Arsenal", price: 9.5, photo: "https://media.api-sports.io/football/players/175008.png" },
    { id: "de_025", name: "Denis Undav", pos: "FWD", age: 28, nation: "Germany", club: "Stuttgart", price: 6.5, photo: "https://media.api-sports.io/football/players/278892.png" },
    { id: "de_026", name: "Nick Woltemeade", pos: "FWD", age: 22, nation: "Germany", club: "Stuttgart", price: 5.5, photo: "https://media.api-sports.io/football/players/380118.png" },
  ],

  Portugal: [
    { id: "pt_001", name: "Diogo Costa", pos: "GK", age: 25, nation: "Portugal", club: "Porto", price: 5.5, photo: "https://media.api-sports.io/football/players/284084.png" },
    { id: "pt_002", name: "Rui Patricio", pos: "GK", age: 38, nation: "Portugal", club: "Roma", price: 4.0, photo: "https://media.api-sports.io/football/players/1468.png" },
    { id: "pt_003", name: "Jose Sa", pos: "GK", age: 31, nation: "Portugal", club: "Wolves", price: 4.5, photo: "https://media.api-sports.io/football/players/25765.png" },
    { id: "pt_004", name: "Ruben Dias", pos: "DEF", age: 27, nation: "Portugal", club: "Manchester City", price: 7.0, photo: "https://media.api-sports.io/football/players/214062.png" },
    { id: "pt_005", name: "Joao Cancelo", pos: "DEF", age: 31, nation: "Portugal", club: "Barcelona", price: 7.0, photo: "https://media.api-sports.io/football/players/2935.png" },
    { id: "pt_006", name: "Nuno Mendes", pos: "DEF", age: 22, nation: "Portugal", club: "PSG", price: 6.5, photo: "https://media.api-sports.io/football/players/306974.png" },
    { id: "pt_007", name: "Diogo Dalot", pos: "DEF", age: 25, nation: "Portugal", club: "Manchester United", price: 5.5, photo: "https://media.api-sports.io/football/players/183985.png" },
    { id: "pt_008", name: "Goncalo Inacio", pos: "DEF", age: 23, nation: "Portugal", club: "Sporting CP", price: 5.5, photo: "https://media.api-sports.io/football/players/307539.png" },
    { id: "pt_009", name: "Renato Veiga", pos: "DEF", age: 21, nation: "Portugal", club: "Chelsea", price: 5.0, photo: "https://media.api-sports.io/football/players/395512.png" },
    { id: "pt_010", name: "Nelson Semedo", pos: "DEF", age: 31, nation: "Portugal", club: "Wolves", price: 5.0, photo: "https://media.api-sports.io/football/players/1523.png" },
    { id: "pt_011", name: "Tomas Araujo", pos: "DEF", age: 23, nation: "Portugal", club: "Barcelona", price: 5.0, photo: "https://media.api-sports.io/football/players/323479.png" },
    { id: "pt_012", name: "Matheus Nunes", pos: "MID", age: 26, nation: "Portugal", club: "Manchester City", price: 5.5, photo: "https://media.api-sports.io/football/players/310165.png" },
    { id: "pt_013", name: "Bruno Fernandes", pos: "MID", age: 30, nation: "Portugal", club: "Manchester United", price: 10.0, photo: "https://media.api-sports.io/football/players/521.png" },
    { id: "pt_014", name: "Bernardo Silva", pos: "MID", age: 30, nation: "Portugal", club: "Manchester City", price: 9.5, photo: "https://media.api-sports.io/football/players/1513.png" },
    { id: "pt_015", name: "Joao Neves", pos: "MID", age: 20, nation: "Portugal", club: "PSG", price: 7.5, photo: "https://media.api-sports.io/football/players/399765.png" },
    { id: "pt_016", name: "Vitinha", pos: "MID", age: 24, nation: "Portugal", club: "PSG", price: 7.0, photo: "https://media.api-sports.io/football/players/310166.png" },
    { id: "pt_017", name: "Ruben Neves", pos: "MID", age: 27, nation: "Portugal", club: "Al Hilal", price: 6.5, photo: "https://media.api-sports.io/football/players/1522.png" },
    { id: "pt_018", name: "Samu Costa", pos: "MID", age: 24, nation: "Portugal", club: "Famalicao", price: 5.0, photo: "https://media.api-sports.io/football/players/306972.png" },
    { id: "pt_019", name: "Cristiano Ronaldo", pos: "FWD", age: 41, nation: "Portugal", club: "Al Nassr", price: 10.5, photo: "https://media.api-sports.io/football/players/874.png" },
    { id: "pt_020", name: "Rafael Leao", pos: "FWD", age: 25, nation: "Portugal", club: "AC Milan", price: 10.0, photo: "https://media.api-sports.io/football/players/215914.png" },
    { id: "pt_021", name: "Pedro Neto", pos: "FWD", age: 24, nation: "Portugal", club: "Chelsea", price: 8.5, photo: "https://media.api-sports.io/football/players/246669.png" },
    { id: "pt_022", name: "Joao Felix", pos: "FWD", age: 25, nation: "Portugal", club: "Chelsea", price: 8.0, photo: "https://media.api-sports.io/football/players/211028.png" },
    { id: "pt_023", name: "Francisco Conceicao", pos: "FWD", age: 22, nation: "Portugal", club: "Juventus", price: 7.5, photo: "https://media.api-sports.io/football/players/373862.png" },
    { id: "pt_024", name: "Goncalo Ramos", pos: "FWD", age: 23, nation: "Portugal", club: "PSG", price: 8.0, photo: "https://media.api-sports.io/football/players/350483.png" },
    { id: "pt_025", name: "Goncalo Guedes", pos: "FWD", age: 28, nation: "Portugal", club: "Benfica", price: 6.5, photo: "https://media.api-sports.io/football/players/1521.png" },
    { id: "pt_026", name: "Francisco Trincao", pos: "FWD", age: 25, nation: "Portugal", club: "Sporting CP", price: 6.5, photo: "https://media.api-sports.io/football/players/246668.png" },
  ],

  Spain: [
    { id: "es_001", name: "Unai Simon", pos: "GK", age: 27, nation: "Spain", club: "Athletic Bilbao", price: 5.5, photo: "https://media.api-sports.io/football/players/200855.png" },
    { id: "es_002", name: "David Raya", pos: "GK", age: 29, nation: "Spain", club: "Arsenal", price: 5.5, photo: "https://media.api-sports.io/football/players/35839.png" },
    { id: "es_003", name: "Alex Remiro", pos: "GK", age: 29, nation: "Spain", club: "Real Sociedad", price: 4.5, photo: "https://media.api-sports.io/football/players/162276.png" },
    { id: "es_004", name: "Dani Carvajal", pos: "DEF", age: 33, nation: "Spain", club: "Real Madrid", price: 6.0, photo: "https://media.api-sports.io/football/players/19257.png" },
    { id: "es_005", name: "Alejandro Grimaldo", pos: "DEF", age: 29, nation: "Spain", club: "Bayer Leverkusen", price: 6.5, photo: "https://media.api-sports.io/football/players/90.png" },
    { id: "es_006", name: "Robin Le Normand", pos: "DEF", age: 27, nation: "Spain", club: "Atletico Madrid", price: 5.5, photo: "https://media.api-sports.io/football/players/215312.png" },
    { id: "es_007", name: "Pau Cubarsi", pos: "DEF", age: 18, nation: "Spain", club: "Barcelona", price: 5.5, photo: "https://media.api-sports.io/football/players/432864.png" },
    { id: "es_008", name: "Aymeric Laporte", pos: "DEF", age: 31, nation: "Spain", club: "Al Nassr", price: 5.0, photo: "https://media.api-sports.io/football/players/670.png" },
    { id: "es_009", name: "Marc Cucurella", pos: "DEF", age: 26, nation: "Spain", club: "Chelsea", price: 5.5, photo: "https://media.api-sports.io/football/players/278893.png" },
    { id: "es_010", name: "Pedri", pos: "MID", age: 23, nation: "Spain", club: "Barcelona", price: 10.0, photo: "https://media.api-sports.io/football/players/306975.png" },
    { id: "es_011", name: "Gavi", pos: "MID", age: 24, nation: "Spain", club: "Barcelona", price: 8.5, photo: "https://media.api-sports.io/football/players/306970.png" },
    { id: "es_012", name: "Rodri", pos: "MID", age: 28, nation: "Spain", club: "Manchester City", price: 9.5, photo: "https://media.api-sports.io/football/players/200856.png" },
    { id: "es_013", name: "Fabian Ruiz", pos: "MID", age: 28, nation: "Spain", club: "PSG", price: 7.5, photo: "https://media.api-sports.io/football/players/163053.png" },
    { id: "es_014", name: "Mikel Merino", pos: "MID", age: 28, nation: "Spain", club: "Arsenal", price: 7.0, photo: "https://media.api-sports.io/football/players/162277.png" },
    { id: "es_015", name: "Dani Olmo", pos: "MID", age: 26, nation: "Spain", club: "Barcelona", price: 8.0, photo: "https://media.api-sports.io/football/players/216956.png" },
    { id: "es_016", name: "Lamine Yamal", pos: "FWD", age: 18, nation: "Spain", club: "Barcelona", price: 11.5, photo: "https://media.api-sports.io/football/players/462039.png" },
    { id: "es_017", name: "Alvaro Morata", pos: "FWD", age: 32, nation: "Spain", club: "AC Milan", price: 7.0, photo: "https://media.api-sports.io/football/players/726.png" },
    { id: "es_018", name: "Nico Williams", pos: "FWD", age: 22, nation: "Spain", club: "Athletic Bilbao", price: 9.0, photo: "https://media.api-sports.io/football/players/388127.png" },
    { id: "es_019", name: "Ferran Torres", pos: "FWD", age: 25, nation: "Spain", club: "Barcelona", price: 7.5, photo: "https://media.api-sports.io/football/players/284033.png" },
    { id: "es_020", name: "Mikel Oyarzabal", pos: "FWD", age: 27, nation: "Spain", club: "Real Sociedad", price: 7.5, photo: "https://media.api-sports.io/football/players/163055.png" },
    { id: "es_021", name: "Bryan Zaragoza", pos: "FWD", age: 23, nation: "Spain", club: "Bayern Munich", price: 6.5, photo: "https://media.api-sports.io/football/players/380119.png" },
  ],

  Argentina: [
    { id: "ar_001", name: "Emiliano Martinez", pos: "GK", age: 32, nation: "Argentina", club: "Aston Villa", price: 6.5, photo: "https://media.api-sports.io/football/players/13220.png" },
    { id: "ar_002", name: "Franco Armani", pos: "GK", age: 38, nation: "Argentina", club: "River Plate", price: 4.5, photo: "https://media.api-sports.io/football/players/6291.png" },
    { id: "ar_003", name: "Geronimo Rulli", pos: "GK", age: 32, nation: "Argentina", club: "Ajax", price: 4.5, photo: "https://media.api-sports.io/football/players/2979.png" },
    { id: "ar_004", name: "Cristian Romero", pos: "DEF", age: 26, nation: "Argentina", club: "Tottenham", price: 7.0, photo: "https://media.api-sports.io/football/players/247234.png" },
    { id: "ar_005", name: "Lisandro Martinez", pos: "DEF", age: 27, nation: "Argentina", club: "Manchester United", price: 6.5, photo: "https://media.api-sports.io/football/players/259332.png" },
    { id: "ar_006", name: "Nicolas Otamendi", pos: "DEF", age: 37, nation: "Argentina", club: "Benfica", price: 5.0, photo: "https://media.api-sports.io/football/players/890.png" },
    { id: "ar_007", name: "Gonzalo Montiel", pos: "DEF", age: 27, nation: "Argentina", club: "Nottingham Forest", price: 5.0, photo: "https://media.api-sports.io/football/players/237799.png" },
    { id: "ar_008", name: "Nicolas Tagliafico", pos: "DEF", age: 32, nation: "Argentina", club: "Lyon", price: 5.0, photo: "https://media.api-sports.io/football/players/9512.png" },
    { id: "ar_009", name: "Nahuel Molina", pos: "DEF", age: 26, nation: "Argentina", club: "Atletico Madrid", price: 5.5, photo: "https://media.api-sports.io/football/players/237798.png" },
    { id: "ar_010", name: "Rodrigo De Paul", pos: "MID", age: 30, nation: "Argentina", club: "Atletico Madrid", price: 7.5, photo: "https://media.api-sports.io/football/players/6570.png" },
    { id: "ar_011", name: "Alexis Mac Allister", pos: "MID", age: 26, nation: "Argentina", club: "Liverpool", price: 8.0, photo: "https://media.api-sports.io/football/players/246466.png" },
    { id: "ar_012", name: "Enzo Fernandez", pos: "MID", age: 24, nation: "Argentina", club: "Chelsea", price: 8.5, photo: "https://media.api-sports.io/football/players/350487.png" },
    { id: "ar_013", name: "Leandro Paredes", pos: "MID", age: 30, nation: "Argentina", club: "Roma", price: 6.0, photo: "https://media.api-sports.io/football/players/2309.png" },
    { id: "ar_014", name: "Giovani Lo Celso", pos: "MID", age: 28, nation: "Argentina", club: "Tottenham", price: 6.5, photo: "https://media.api-sports.io/football/players/152807.png" },
    { id: "ar_015", name: "Lionel Messi", pos: "FWD", age: 38, nation: "Argentina", club: "Inter Miami", price: 11.0, photo: "https://media.api-sports.io/football/players/154.png" },
    { id: "ar_016", name: "Lautaro Martinez", pos: "FWD", age: 27, nation: "Argentina", club: "Inter Milan", price: 12.0, photo: "https://media.api-sports.io/football/players/184390.png" },
    { id: "ar_017", name: "Julian Alvarez", pos: "FWD", age: 24, nation: "Argentina", club: "Atletico Madrid", price: 11.0, photo: "https://media.api-sports.io/football/players/346101.png" },
    { id: "ar_018", name: "Angel Di Maria", pos: "FWD", age: 36, nation: "Argentina", club: "Benfica", price: 7.0, photo: "https://media.api-sports.io/football/players/1455.png" },
    { id: "ar_019", name: "Nicolas Gonzalez", pos: "FWD", age: 26, nation: "Argentina", club: "Juventus", price: 7.5, photo: "https://media.api-sports.io/football/players/214053.png" },
    { id: "ar_020", name: "Alejandro Garnacho", pos: "FWD", age: 20, nation: "Argentina", club: "Manchester United", price: 8.0, photo: "https://media.api-sports.io/football/players/378984.png" },
    { id: "ar_021", name: "Paulo Dybala", pos: "FWD", age: 31, nation: "Argentina", club: "Roma", price: 8.0, photo: "https://media.api-sports.io/football/players/1485.png" },
  ],

  Belgium: [
    { id: "be_001", name: "Thibaut Courtois", pos: "GK", age: 33, nation: "Belgium", club: "Real Madrid", price: 6.5, photo: "https://media.api-sports.io/football/players/2935.png" },
    { id: "be_002", name: "Senne Lammens", pos: "GK", age: 24, nation: "Belgium", club: "Antwerp", price: 4.0, photo: "https://media.api-sports.io/football/players/387120.png" },
    { id: "be_003", name: "Mike Penders", pos: "GK", age: 20, nation: "Belgium", club: "Chelsea", price: 4.0, photo: "https://media.api-sports.io/football/players/432870.png" },
    { id: "be_004", name: "Thomas Meunier", pos: "DEF", age: 32, nation: "Belgium", club: "Trabzonspor", price: 5.0, photo: "https://media.api-sports.io/football/players/2937.png" },
    { id: "be_005", name: "Timothy Castagne", pos: "DEF", age: 29, nation: "Belgium", club: "Fulham", price: 5.5, photo: "https://media.api-sports.io/football/players/155843.png" },
    { id: "be_006", name: "Arthur Theate", pos: "DEF", age: 24, nation: "Belgium", club: "Rennes", price: 5.0, photo: "https://media.api-sports.io/football/players/327557.png" },
    { id: "be_007", name: "Zeno Debast", pos: "DEF", age: 21, nation: "Belgium", club: "Sporting CP", price: 5.0, photo: "https://media.api-sports.io/football/players/380121.png" },
    { id: "be_008", name: "Maxim De Cuyper", pos: "DEF", age: 23, nation: "Belgium", club: "Club Brugge", price: 5.0, photo: "https://media.api-sports.io/football/players/394234.png" },
    { id: "be_009", name: "Brandon Mechele", pos: "DEF", age: 32, nation: "Belgium", club: "Club Brugge", price: 4.5, photo: "https://media.api-sports.io/football/players/155844.png" },
    { id: "be_010", name: "Koni De Winter", pos: "DEF", age: 22, nation: "Belgium", club: "Genoa", price: 4.5, photo: "https://media.api-sports.io/football/players/380122.png" },
    { id: "be_011", name: "Kevin De Bruyne", pos: "MID", age: 33, nation: "Belgium", club: "Napoli", price: 10.5, photo: "https://media.api-sports.io/football/players/627.png" },
    { id: "be_012", name: "Axel Witsel", pos: "MID", age: 35, nation: "Belgium", club: "Atletico Madrid", price: 5.5, photo: "https://media.api-sports.io/football/players/716.png" },
    { id: "be_013", name: "Youri Tielemans", pos: "MID", age: 27, nation: "Belgium", club: "Aston Villa", price: 7.0, photo: "https://media.api-sports.io/football/players/2936.png" },
    { id: "be_014", name: "Amadou Onana", pos: "MID", age: 23, nation: "Belgium", club: "Aston Villa", price: 7.5, photo: "https://media.api-sports.io/football/players/380120.png" },
    { id: "be_015", name: "Hans Vanaken", pos: "MID", age: 31, nation: "Belgium", club: "Club Brugge", price: 6.0, photo: "https://media.api-sports.io/football/players/2940.png" },
    { id: "be_016", name: "Nicolas Raskin", pos: "MID", age: 22, nation: "Belgium", club: "Rangers", price: 5.5, photo: "https://media.api-sports.io/football/players/373870.png" },
    { id: "be_017", name: "Romelu Lukaku", pos: "FWD", age: 31, nation: "Belgium", club: "Napoli", price: 9.5, photo: "https://media.api-sports.io/football/players/306.png" },
    { id: "be_018", name: "Leandro Trossard", pos: "FWD", age: 29, nation: "Belgium", club: "Arsenal", price: 8.0, photo: "https://media.api-sports.io/football/players/162279.png" },
    { id: "be_019", name: "Jeremy Doku", pos: "FWD", age: 22, nation: "Belgium", club: "Manchester City", price: 9.0, photo: "https://media.api-sports.io/football/players/283087.png" },
    { id: "be_020", name: "Dodi Lukebakio", pos: "FWD", age: 26, nation: "Belgium", club: "Sevilla", price: 6.5, photo: "https://media.api-sports.io/football/players/163058.png" },
    { id: "be_021", name: "Charles De Ketelaere", pos: "FWD", age: 24, nation: "Belgium", club: "Atalanta", price: 7.5, photo: "https://media.api-sports.io/football/players/350488.png" },
    { id: "be_022", name: "Alexis Saelemakers", pos: "FWD", age: 25, nation: "Belgium", club: "AC Milan", price: 7.0, photo: "https://media.api-sports.io/football/players/246482.png" },
  ],

  Netherlands: [
    { id: "nl_001", name: "Bart Verbruggen", pos: "GK", age: 22, nation: "Netherlands", club: "Brighton", price: 5.0, photo: "https://media.api-sports.io/football/players/388128.png" },
    { id: "nl_002", name: "Mark Flekken", pos: "GK", age: 31, nation: "Netherlands", club: "Brentford", price: 4.5, photo: "https://media.api-sports.io/football/players/155818.png" },
    { id: "nl_003", name: "Virgil van Dijk", pos: "DEF", age: 33, nation: "Netherlands", club: "Liverpool", price: 7.0, photo: "https://media.api-sports.io/football/players/1268.png" },
    { id: "nl_004", name: "Matthijs de Ligt", pos: "DEF", age: 25, nation: "Netherlands", club: "Manchester United", price: 6.0, photo: "https://media.api-sports.io/football/players/160157.png" },
    { id: "nl_005", name: "Denzel Dumfries", pos: "DEF", age: 28, nation: "Netherlands", club: "Inter Milan", price: 6.0, photo: "https://media.api-sports.io/football/players/162281.png" },
    { id: "nl_006", name: "Nathan Ake", pos: "DEF", age: 30, nation: "Netherlands", club: "Manchester City", price: 5.5, photo: "https://media.api-sports.io/football/players/603.png" },
    { id: "nl_007", name: "Jurrien Timber", pos: "DEF", age: 23, nation: "Netherlands", club: "Arsenal", price: 6.0, photo: "https://media.api-sports.io/football/players/350490.png" },
    { id: "nl_008", name: "Stefan de Vrij", pos: "DEF", age: 32, nation: "Netherlands", club: "Inter Milan", price: 5.0, photo: "https://media.api-sports.io/football/players/2941.png" },
    { id: "nl_009", name: "Frenkie de Jong", pos: "MID", age: 28, nation: "Netherlands", club: "Barcelona", price: 9.0, photo: "https://media.api-sports.io/football/players/183985.png" },
    { id: "nl_010", name: "Tijjani Reijnders", pos: "MID", age: 26, nation: "Netherlands", club: "AC Milan", price: 8.0, photo: "https://media.api-sports.io/football/players/373862.png" },
    { id: "nl_011", name: "Teun Koopmeiners", pos: "MID", age: 26, nation: "Netherlands", club: "Juventus", price: 8.0, photo: "https://media.api-sports.io/football/players/280693.png" },
    { id: "nl_012", name: "Xavi Simons", pos: "MID", age: 22, nation: "Netherlands", club: "PSG", price: 9.0, photo: "https://media.api-sports.io/football/players/342026.png" },
    { id: "nl_013", name: "Ryan Gravenberch", pos: "MID", age: 22, nation: "Netherlands", club: "Liverpool", price: 7.5, photo: "https://media.api-sports.io/football/players/280691.png" },
    { id: "nl_014", name: "Quinten Timber", pos: "MID", age: 22, nation: "Netherlands", club: "Arsenal", price: 6.0, photo: "https://media.api-sports.io/football/players/387024.png" },
    { id: "nl_015", name: "Cody Gakpo", pos: "FWD", age: 25, nation: "Netherlands", club: "Liverpool", price: 9.5, photo: "https://media.api-sports.io/football/players/280690.png" },
    { id: "nl_016", name: "Memphis Depay", pos: "FWD", age: 31, nation: "Netherlands", club: "Corinthians", price: 7.0, photo: "https://media.api-sports.io/football/players/521.png" },
    { id: "nl_017", name: "Donyell Malen", pos: "FWD", age: 26, nation: "Netherlands", club: "Aston Villa", price: 7.0, photo: "https://media.api-sports.io/football/players/236660.png" },
    { id: "nl_018", name: "Brian Brobbey", pos: "FWD", age: 23, nation: "Netherlands", club: "Ajax", price: 7.0, photo: "https://media.api-sports.io/football/players/307524.png" },
    { id: "nl_019", name: "Wout Weghorst", pos: "FWD", age: 32, nation: "Netherlands", club: "Burnley", price: 5.5, photo: "https://media.api-sports.io/football/players/19197.png" },
  ],

  Croatia: [
    { id: "hr_001", name: "Dominik Livakovic", pos: "GK", age: 29, nation: "Croatia", club: "Fenerbahce", price: 5.5, photo: "https://media.api-sports.io/football/players/162277.png" },
    { id: "hr_002", name: "Dominik Kotarski", pos: "GK", age: 26, nation: "Croatia", club: "Club Brugge", price: 4.5, photo: "https://media.api-sports.io/football/players/278895.png" },
    { id: "hr_003", name: "Ivor Pandur", pos: "GK", age: 23, nation: "Croatia", club: "Lille", price: 4.0, photo: "https://media.api-sports.io/football/players/387025.png" },
    { id: "hr_004", name: "Josko Gvardiol", pos: "DEF", age: 23, nation: "Croatia", club: "Manchester City", price: 8.0, photo: "https://media.api-sports.io/football/players/350492.png" },
    { id: "hr_005", name: "Duje Caleta-Car", pos: "DEF", age: 28, nation: "Croatia", club: "Southampton", price: 5.0, photo: "https://media.api-sports.io/football/players/155828.png" },
    { id: "hr_006", name: "Josip Stanisic", pos: "DEF", age: 24, nation: "Croatia", club: "Bayer Leverkusen", price: 5.5, photo: "https://media.api-sports.io/football/players/313555.png" },
    { id: "hr_007", name: "Marin Pongracic", pos: "DEF", age: 27, nation: "Croatia", club: "Fiorentina", price: 5.0, photo: "https://media.api-sports.io/football/players/155844.png" },
    { id: "hr_008", name: "Martin Erlic", pos: "DEF", age: 26, nation: "Croatia", club: "Sassuolo", price: 4.5, photo: "https://media.api-sports.io/football/players/200856.png" },
    { id: "hr_009", name: "Luka Vuskovic", pos: "DEF", age: 18, nation: "Croatia", club: "Tottenham", price: 5.0, photo: "https://media.api-sports.io/football/players/403216.png" },
    { id: "hr_010", name: "Luka Modric", pos: "MID", age: 40, nation: "Croatia", club: "Real Madrid", price: 9.5, photo: "https://media.api-sports.io/football/players/1468.png" },
    { id: "hr_011", name: "Mateo Kovacic", pos: "MID", age: 31, nation: "Croatia", club: "Manchester City", price: 7.5, photo: "https://media.api-sports.io/football/players/184.png" },
    { id: "hr_012", name: "Marcelo Brozovic", pos: "MID", age: 31, nation: "Croatia", club: "Al Nassr", price: 6.5, photo: "https://media.api-sports.io/football/players/1513.png" },
    { id: "hr_013", name: "Mario Pasalic", pos: "MID", age: 29, nation: "Croatia", club: "Atalanta", price: 6.5, photo: "https://media.api-sports.io/football/players/9498.png" },
    { id: "hr_014", name: "Lovro Majer", pos: "MID", age: 27, nation: "Croatia", club: "Wolves", price: 6.5, photo: "https://media.api-sports.io/football/players/307537.png" },
    { id: "hr_015", name: "Ivan Perisic", pos: "MID", age: 35, nation: "Croatia", club: "Hajduk Split", price: 6.0, photo: "https://media.api-sports.io/football/players/521.png" },
    { id: "hr_016", name: "Andrej Kramaric", pos: "FWD", age: 33, nation: "Croatia", club: "Hoffenheim", price: 7.0, photo: "https://media.api-sports.io/football/players/88.png" },
    { id: "hr_017", name: "Bruno Petkovic", pos: "FWD", age: 31, nation: "Croatia", club: "Dinamo Zagreb", price: 6.0, photo: "https://media.api-sports.io/football/players/155827.png" },
    { id: "hr_018", name: "Ivan Zucko", pos: "FWD", age: 24, nation: "Croatia", club: "Augsburg", price: 5.5, photo: "https://media.api-sports.io/football/players/367083.png" },
  ],
};

// Helpers
export const getAllPlayers = () => Object.values(NATIONS).flat();

export const getByPosition = (pos) =>
  getAllPlayers().filter(p => p.pos === pos);

export const getNationList = () => Object.keys(NATIONS);

export const getByNation = (nation) => NATIONS[nation] || [];
